### ISSUE TITLE
Make StatsEntry working with websockets

### ISSUE THREAD

**Issue by aaronorosen2** [Dreampotential-org/meylordrive#3]
Task we have is to be able to run python stats-agent.py and python code/manage.py runserver and be able to have entries here populate https://github.com/Dreampotential-org/meylordrive/blob/master/codes/server_websocket/consumers.py#L75

**Comment by aaronorosen2** [comment]
I have updated this some more here is how to reproduce this issue: 

```
(venv) arosen@node1:~/meylordrive$ python stats-agent.py 
[selector_events.py:__init__():line 54] DEBUG: Using selector: EpollSelector
[protocol.py:__init__():line 255] DEBUG: = connection is CONNECTING
**[client.py:write_http_request():line 115] DEBUG: > GET /ws/chat/ HTTP/1.1**
[client.py:write_http_request():line 117] DEBUG: > Host: 127.0.0.1:8000
[client.py:write_http_request():line 117] DEBUG: > Upgrade: websocket
[client.py:write_http_request():line 117] DEBUG: > Connection: Upgrade
[client.py:write_http_request():line 117] DEBUG: > Sec-WebSocket-Key: NtSQuRE0cWlivjiwgkV6dw==
[client.py:write_http_request():line 117] DEBUG: > Sec-WebSocket-Version: 13
[client.py:write_http_request():line 117] DEBUG: > Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
[client.py:write_http_request():line 117] DEBUG: > User-Agent: Python/3.10 websockets/11.0.3
[client.py:read_http_response():line 148] DEBUG: < HTTP/1.1 404 Not Found
[client.py:read_http_response():line 150] DEBUG: < Server: gunicorn
[client.py:read_http_response():line 150] DEBUG: < Date: Mon, 06 Nov 2023 18:38:36 GMT
[client.py:read_http_response():line 150] DEBUG: < Connection: close
[client.py:read_http_response():line 150] DEBUG: < Content-Type: text/html
[client.py:read_http_response():line 150] DEBUG: < X-Frame-Options: ALLOW-FROM HTTPS://APP.REALTORSTAT.COM/
[client.py:read_http_response():line 150] DEBUG: < Content-Length: 7526
[client.py:read_http_response():line 150] DEBUG: < X-Content-Type-Options: nosniff
[client.py:read_http_response():line 150] DEBUG: < Referrer-Policy: same-origin
[client.py:read_http_response():line 150] DEBUG: < Vary: Origin
[protocol.py:fail_connection():line 1409] DEBUG: ! failing connection with code 1006
[protocol.py:close_connection():line 1320] DEBUG: x half-closing TCP connection
[protocol.py:connection_lost():line 1494] DEBUG: = connection is CLOSED
Traceback (most recent call last):
  File "/users/arosen/meylordrive/stats-agent.py", line 222, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/users/arosen/meylordrive/stats-agent.py", line 201, in main
    async with websockets.connect(uri) as websocket:
  File "/users/arosen/meylordrive/venv/lib/python3.10/site-packages/websockets/legacy/client.py", line 637, in __aenter__
    return await self
  File "/users/arosen/meylordrive/venv/lib/python3.10/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/users/arosen/meylordrive/venv/lib/python3.10/site-packages/websockets/legacy/client.py", line 662, in __await_impl__
    await protocol.handshake(
  File "/users/arosen/meylordrive/venv/lib/python3.10/site-packages/websockets/legacy/client.py", line 329, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 404
```

**Comment by aaronorosen2** [comment]
https://github.com/Dreampotential-org/meylordrive/blob/master/codes/server_agent/routing.py#L6 Here is where: 
```
    re_path(r'ws/chat/$', consumers.ServerAgentConsumer.as_asgi()),
```
